### ISSUE TITLE
The parameter javaVersion has an invalid value

### ISSUE THREAD

**Issue by request92** [Microsoft/azure-maven-plugins#612]
### Plugin name and version
azure-webapp-maven-plugin 1.5.4

### Plugin configuration in your `pom.xml`
    <plugins>
        <plugin>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-webapp-maven-plugin</artifactId>
            <version>1.5.4</version>
            <configuration>
                <schemaVersion>v2</schemaVersion>
                <resourceGroup>${RESOURCEGROUP_NAME}</resourceGroup>
                <appName>${WEBAPP_NAME}</appName>
                <runtime>
                    <os>linux</os>
                    <javaVersion>jre8</javaVersion>
                    <webContainer>tomcat 8.5</webContainer>
                </runtime>
                <deployment>
                    <resources>
                        <resource>
                            <directory>${project.basedir}/target</directory>
                            <includes>
                                <include>*.war</include>
                            </includes>
                        </resource>
                    </resources>
                </deployment>
            </configuration>
        </plugin

### Expected behavior
The application is deployed.
this configuration worked for several months and recently, I still get this error message.

### Actual behavior
Error message : 
`	[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.5.4:deploy (default-cli) on project ui5.labdfg: Status code 400, {"Code":"BadRequest","Message":"The parameter javaVersion has an invalid value.","Target":null,"Details":[{"Message":"The parameter javaVersion has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"01007","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["javaVersion"],"Code":"BadRequest","Message":"The parameter javaVersion has an invalid value."}}],"Innererror":null} -> [Help 1]
`

By removong javaVersion I obtain this error  

`[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.5.4:deploy (default-cli) on project ui5.labdfg: Unknown value of <javaVersion>. Supported values is jre8 -> [Help 1]`

The server is an Web App on Linux with Tomcat 8.5

### Steps to reproduce the problem
Same Plugin configuration

**Comment by kunleawotunbo** [comment]
I am having the same error. I was about to open an issue here.
I have a running app on Azure, I updated my code without changing any configuration using
 `mvn azure-webapp:deploy`
But I got the above error.

**Comment by request92** [comment]
It may be related to recent changes in 
https://github.com/Azure-App-Service/tomcat

I'm stuck with this anomaly, if you've found a way to fix it,  please add a comment

**Comment by ernesto-arm** [comment]
I have the same problem with <linuxRuntime>jre8</linuxRuntime>. 
It has stopped working today. Found out because my CI pipeline has failed this morning.

**Comment by Flanker32** [comment]
@request92 @kunleawotunbo @ernesto-arm  Thanks for your report, my team is working with app service team to investigate this issue, will update here once we get any progress.

**Comment by sshaw8** [comment]
I am facing the same issue since today morning. 

        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Status code 400, {"Code":"BadRequest","Message":"The parameter javaVersion has an invalid value.","Target":null,"Details":[{"Message":"The parameter javaVersion has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"01007","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["javaVersion"],"Code":"BadRequest","Message":"The parameter javaVersion has an invalid value."}}],"Innererror":null}
        at com.microsoft.azure.maven.AbstractAzureMojo.handleException(AbstractAzureMojo.java:374)
        at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:314)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: com.microsoft.azure.management.appservice.DefaultErrorResponseException: Status code 400, {"Code":"BadRequest","Message":"The parameter javaVersion has an invalid value.","Target":null,"Details":[{"Message":"The parameter javaVersion has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"01007","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["javaVersion"],"Code":"BadRequest","Message":"The parameter javaVersion has an invalid value."}}],"Innererror":null}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
        at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
        at com.microsoft.azure.management.appservice.implementation.WebAppsInner.createOrUpdateConfigurationDelegate(WebAppsInner.java:5756)

**Comment by kunleawotunbo** [comment]
> @request92 @kunleawotunbo @ernesto-arm Thanks for your report, my team is working with app service team to investigate this issue, will update here once we get any progress.

Please is there an alternative way to deploy my application pending the time the issue is being resolved. I need to deploy my update to the server.

**Comment by joemat** [comment]
I'm having the same issue. Only 'workaround' I found was deleting the app and deploying it new. :(

Would be good to know a better workaround.

**Comment by sshaw8** [comment]
@kunleawotunbo 
You can deploy your app using FTP. Follow the link 
https://docs.microsoft.com/en-us/azure/app-service/deploy-ftp

**Comment by JasonFreeberg** [comment]
Hi everyone, our engineering team is aware of the problem and we are actively working on a fix. To mitigate the problem, please deploy your JAR or WAR using ZIP-deploy or WAR-deploy respectively ([documentation here](https://docs.microsoft.com/en-us/azure/app-service/deploy-zip
)).

We do **not** advise deploying JARs or WARs via FTP.

**Comment by marceloverdijk** [comment]
@Flanker32 @JasonFreeberg Any update on this?

**Comment by ubamrein** [comment]
@JasonFreeberg  @Flanker32 @marceloverdijk 

Facing the same issue right now. But I discovered that if you remove the "<schemaVersion>" property from the pom, it actually does deploy something to azure. Although in that case, for some reason it starts the "default.jar" instead of our deployed one. In the logs I can see that the jar file is actually copied. Also locally the zip file which is created and uploaded seems to be configured correctly...

**Comment by request92** [comment]
> # Mitigation Instructions
> Hi everyone, our engineering team is aware of the problem and we are actively working on a fix. To mitigate the problem, please deploy your JAR or WAR using ZIP-deploy or WAR-deploy respectively ([documentation here](https://docs.microsoft.com/en-us/azure/app-service/deploy-zip)).
> 
> We do **not** advise deploying JARs or WARs via FTP.
> 
> @kunleawotunbo @request92

Thanks @JasonFreeberg I looked at the documentation, it's not easy but I succeeded with curl
`curl -X POST -u $SERVER --data-binary @"MYAPP.war" https://SERVER.scm.azurewebsites.net/api/wardeploy?name=MYAPP`
I hope this will be resolved quickly.

**Comment by tim-slaton-bib** [comment]
> @JasonFreeberg @Flanker32 @marceloverdijk
> 
> Facing the same issue right now. But I discovered that if you remove the "schemaVersion" property from the pom, it actually does deploy something to azure. Although in that case, for some reason it starts the "default.jar" instead of our deployed one. In the logs I can see that the jar file is actually copied. Also locally the zip file which is created and uploaded seems to be configured correctly...

Doing this (removing schemaVersion) plus also adding finalName=app under build worked for me.
```xml
<build>
<finalName>app</finalName>
...

</build>
``` 
Only the name "app" made it work for me. I tried other names. In my CI output, it says "Generating web.config for Web App on Windows" which is a little strange because my Web App is Linux. However, these changes made my deployment succeed and now my application works.

**Comment by ubamrein** [comment]
@JasonFreeberg 

Ok, I found a fix. The problem has to do with the new scheme update I guess. The appservice with the Java SE docker provided by Microsoft needs an "app.jar" file in the /home/site/wwwroot/ directory. Since some update for some reason the package created by maven isn't renamed to app.jar, when added to the zip. I think it has something to do with the implementation in HandlerFactoryImpl especially with the V2 version, since there the jar isn't renamed. I suppose if you added the V1 scheme explicitly it might work. 

So in the end you just have to add to the pom in the build section

`<finalName>app</finalName>`

Here https://github.com/Azure-App-Service/java/blob/dev/shared/init_container.sh you find the initScript for the docker container, which is created.

**Comment by Flanker32** [comment]
@ubamrein @tim-slaton-bib @request92 @marceloverdijk @sshaw8 @joemat @kunleawotunbo @ernesto-arm Thank you all, our service team has rolled out a fix and this issue should be fixed.

**Comment by request92** [comment]
It works for me again.
thank you for your support.

```
[INFO] Trying to deploy artifact to xxxx...
[INFO] Deploying the war file...
[INFO] Successfully deployed the artifact to https://xxxx.azurewebsites.net
```

**Comment by ubamrein** [comment]
@Flanker32 Could you reference the git commit which resolved it?

**Comment by marceloverdijk** [comment]
@Flanker32 @JasonFreeberg 

I'm still facing an issue.

Before I stumbled against this `javaVersion` issue my Maven pom contained:

```
	<build>
		<plugins>
			<plugin>
				<groupId>com.microsoft.azure</groupId>
				<artifactId>azure-webapp-maven-plugin</artifactId>
				<version>1.5.3</version>
				<configuration>
					<appName>my-backend</appName>
					<appServicePlanName>my-app-service-plan</appServicePlanName>
					<deploymentType>jar</deploymentType>
					<jarFile>build/libs/my-backend-2.0.jar</jarFile>
					<linuxRuntime>jre8</linuxRuntime>
					<pricingTier>B1</pricingTier>
					<region>westeurope</region>
					<resourceGroup>my-resource-group</resourceGroup>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

After facing the issue I looked at https://github.com/Microsoft/azure-maven-plugins/blob/develop/azure-webapp-maven-plugin/README.md and found out that config (since `v2`?) has been change, so I adapted my Maven pom to:

```
	<build>
		<plugins>
			<plugin>
				<groupId>com.microsoft.azure</groupId>
				<artifactId>azure-webapp-maven-plugin</artifactId>
				<version>1.5.4</version>
				<configuration>
					<schemaVersion>v2</schemaVersion>
					<appName>my-backend</appName>
					<appServicePlanName>my-app-service-plan</appServicePlanName>
					<pricingTier>B1</pricingTier>
					<region>westeurope</region>
					<resourceGroup>my-resource-group</resourceGroup>
					<runtime>
						<os>linux</os>
						<javaVersion>jre8</javaVersion>
						<webContainer></webContainer>
					</runtime>
					<deployment>
						<resources>
							<resource>
								<directory>${project.basedir}/build/libs</directory>
								<includes>
									<include>*.jar</include>
								</includes>
							</resource>
						</resources>
					</deployment>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

Now the deployment _seems_ to be successful:

```
[INFO] --- azure-webapp-maven-plugin:1.5.4:deploy (default-cli) @ my-backend ---
[INFO] Authenticate with Azure CLI 2.0
[INFO] Updating target Web App...
[INFO] Successfully updated Web App.
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource to /Users/marceloverdijk/workspace/my-backend-micronaut/target/azure-webapp/my-backend
[INFO] Trying to deploy artifact to my-backend...
[INFO] Deploying the zip package my-backend.zip...
[INFO] Successfully deployed the artifact to https://my-backend.azurewebsites.net
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

However the expected jar is not deployed. 
The app running after the deployment is some old "Hello World" I deployed a while ago...
It was maybe even deployed via FTP I cannot remember anymore, but it was replaced by successful Maven deployments afterwards.

Looking at the logs I also see 

`2019-04-09T18:41:28.188703043Z Launching default.jar`

Some questions:

- The jar in the zip is `my-backend-2.0.jar`, is that ok or is some fixed name expected? Maybe `app.jar` is expected?
- But if above is correct and `app.jar` is expected, what is the reason for giving an include filter?
- Or is my Maven configuration not correct?
- It seems the Azure app resource contains some old files... is there a way to clean it?


Note: I replaced my actual project name with `my-backend` in above log configurations and log snippet. I can share my actual project name privately if needed.

**Comment by marceloverdijk** [comment]
Note when reverting back to the "old" configuration I can deploy successfully.

In that case I also see that `<jarFile>build/libs/my-backend-2.0.jar</jarFile>` is copied to `/target/azure-webapp/my-backend/app.jar`. 

So this seems to behave differently.

**Comment by ubamrein** [comment]
> Note when reverting back to the "old" configuration I can deploy successfully.
> 
> In that case I also see that `<jarFile>build/libs/my-backend-2.0.jar</jarFile>` is copied to `/target/azure-webapp/my-backend/app.jar`.
> 
> So this seems to behave differently.

@Flanker32 @marceloverdijk @request92 

Yeah that's what I meant. In scheme version v2 the copying command does not rename the file. I think the whole V1 to V2 Scheme conversion is broken, and since I couldn't find any commit fixing this bug in this repo, I am not sure if this issue should be closed, or at least a new one should be opened, facing the conversion stuff from V1 to V2.

Though there has been a fix  in the repo for the docker, which is loaded for the Java WebApp environment. That might explain why some stuff works. It now copies the app to default.jar if there is no app.jar found, which I guess in the case of @marceloverdijk leads to running an old version of the app.

But still, if you use a configuration, as it is mentioned in the documentation, there still problems. It is especially frustrating, since V1 is marked as deprecated...

**Comment by Flanker32** [comment]
@marceloverdijk 
1.  'app.jar' is expected, and please set the port to what you use in application, you may refer [here](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#network-endpoint-listening) for azure port information
``` xml
<build> 
    <finalName>app</finalName> <!-- Set name to app.jar -->
    <plugins> 
      <plugin> 
        <groupId>com.microsoft.azure</groupId>  
        <artifactId>azure-webapp-maven-plugin</artifactId>  
        <version>1.5.4</version>  
        <configuration>
          ...
          <appSettings>
              <!-- Set port for app service-->
              <property>
                  <name>PORT</name>
                  <value>8080</value>
              </property>
          </appSettings>
          ...
      </plugin>  
...
```
2. Maven plugin uses zip deploy for the deployment, though App Service will recycled old web container and pick up app.jar once deploy, this will take some time and usually take effect about 5 minutes later, you will still see default.jar is running. I'm working with app service team to fix issue.
3. Maven plugin use filter to get resources need to be packaged with jar files, like configuration files or dependency jars.
4. To clean up old files, you may ssh to app service server and do clean, you may find the ssh web host from azure portal.
![image](https://user-images.githubusercontent.com/12445236/55855956-77d4bd00-5b9b-11e9-9a13-8fab5bf7f859.png)

@ubamrein We didn't imply rename and generage web.config (For windows app service) in V2 Handler as for some old dependency issue, will get them back in later releases, tracked in #616. Sorry for the inconvenience and thanks for your report.

**Comment by request92** [comment]
I'm reopening this issue.
In my case the war deployment seems to work, I will do several tests to check everything

**Comment by ernesto-arm** [comment]
This configuration doesn't work neither
`			<plugin>
				<groupId>com.microsoft.azure</groupId>
				<artifactId>azure-webapp-maven-plugin</artifactId>
				<version>1.5.4</version>
				<configuration>
					
					<authentication>
						<serverId>azure-auth</serverId>
					</authentication>
					
					<linuxRuntime>jre8</linuxRuntime>
					
					<deploymentType>jar</deploymentType>
...
`

**Comment by ernesto-arm** [comment]
This configuration seems to work
```<version>1.5.4</version>
				<configuration>
					<authentication>
						<serverId>azure-auth</serverId>
					</authentication>
					<runtime>
						<os>Linux</os>
						<javaVersion>jre8</javaVersion>
					</runtime>
					<deployment>
						<resources>
							<resource>
								<directory>${project.basedir}/target</directory>
								<includes>
									<include>*.jar</include>
								</includes>
							</resource>
						</resources>
					</deployment>
                                        ....
```
but now the application doesn't start. everything has been uploaded to the server as show the screenshot from the ssh terminal
<img width="515" alt="azure-ssh" src="https://user-images.githubusercontent.com/47353312/55868500-85c71580-5b7c-11e9-831a-6bceb3984fe0.PNG">

Anyone can help? please

**Comment by Flanker32** [comment]
@ernesto-arm According to the config pom it looks like a linux web app but in the screen shot, it's a windows one. Can you share the full configuration part of pom?

**Comment by ernesto-arm** [comment]
@Flanker32 Found the problem... nothing wrong with that configuration. The problem is that the webapp created was a Java 1.8 Tomcat 8.5 not Java SE.
We have recently introduced terraform for automate environment creation and apparently doesn't support JavaSE :(
So moving to War deployment now.

Thanks for your help

**Comment by marceloverdijk** [comment]
@Flanker32 @ubamrein Thx for confirming. The main issue I encountered was actually #616.

I was able to deploy now with `v2` setup after making sure the generated jar was named `app.jar`.
As I'm actually using Gradle to build the jar (and only Maven to deploy it to Azure) the `<finalName>app</finalName>` option was not relevant for me.

**Comment by request92** [comment]
I did the following tests :
* v1 and v2
* war file
* specific target path (not ROOT.war)
* linux / tomcat 8.5-jre8

My v1 pom
```
<plugin>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure-webapp-maven-plugin</artifactId>
	<executions>
		<execution>
			<phase>package</phase>
			<goals>
				<goal>deploy</goal>
			</goals>		
			<configuration>
				<resourceGroup>${RESOURCEGROUP_NAME}</resourceGroup>
				<appName>${WEBAPP_NAME}</appName>
				<linuxRuntime>tomcat 8.5-jre8</linuxRuntime>
				<path>${app.name}</path>
			</configuration>
		</execution>
	</executions>
</plugin>

```

My v2 file
```
<plugin>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure-webapp-maven-plugin</artifactId>
	<version>1.5.4</version>
	<executions>
		<execution>
			<phase>package</phase>
			<goals>
				<goal>deploy</goal>
			</goals>
			<configuration>
				<schemaVersion>v2</schemaVersion>
				<resourceGroup>${RESOURCEGROUP_NAME}</resourceGroup>
				<appName>${WEBAPP_NAME}</appName>
				<runtime>
					<os>linux</os>
					<javaVersion>jre8</javaVersion>
					<webContainer>tomcat 8.5</webContainer>
				</runtime>
				<deployment>
					<resources>
						<resource>
							<directory>${project.basedir}/target</directory>
							<targetPath>${app.name}</targetPath>
							<includes>
								<include>*.war</include>
							</includes>
						</resource>
					</resources>
				</deployment>
			</configuration>
		</execution>
	</executions>
</plugin>

```

In both cases it works
